on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 1"
jobs:
  save:
    name: Save rules
    runs-on: ubuntu-latest
    steps:
    - uses: JamieMagee/wayback@v2.0.0
      with:
        url: |-
          https://wolfy76700.github.io/rules_den.html
          https://wolfy76700.github.io/rules_warrior.html
          https://wolfy76700.github.io/rules_pack.html
        saveErrors: true
        saveOutlinks: true
        saveScreenshot: true